name: Auto update CCBR README


on:
  workflow_dispatch:
  schedule:
    - cron: '30 04 * * 0'

jobs:
  createreadme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Pull Docker
        run: |
          docker pull nciccbr/make_readme:latest
      
      - name: Run Docker to make readme
        env:
            GITHUB_TOKEN: ${{ secrets.OMNITOKEN }}
        run: |
          docker run -e GITHUB_TOKEN=$GITHUB_TOKEN -v ${{ github.workspace }}:/workspace -w /workspace nciccbr/make_readme:latest bash ./assets/make_readme/make_readme.sh

      - name: verify output
        run: |
          cat profile/README.md
  
      - name: Commit  and push changes
        run: |
          git add .
          git commit -m "Commit changes made by createreadme github action."
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ github.token }}
