name: Auto update CCBR README


on:
  push:
    branches:
      - issue-15
  workflow_dispatch:
  schedule:
    - cron: '30 04 * * SUN'

jobs:
  createreadme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./assets/make_readme/requirements.txt
      
      - name: run test 1
        env:
            GITHUB_TOKEN: ${{ github.token }}
        run: |
          python ./assets/make_readme/get_recent_releases_table.py 
      #     docker run -e GITHUB_TOKEN=$GITHUB_TOKEN -v ${{ github.workspace }}:/workspace -w /workspace nciccbr/make_readme:latest bash ./assets/make_readme/make_readme.sh
      # - name: verify output
      #   run: |
      #     cat profile/README.md
    #   - name: Commit changes
    #     uses: stefanzweifel/git-auto-commit-action@v5
    #     env:
    #       GH_TOKEN: ${{ github.token }}
